### ISSUE TITLE
Cancer

### ISSUE THREAD

**Issue by tomislaaaav** [sceptross/AIAD#1]
AIAD is cancer. That fact is true, as you've created a repository with nothing in it, besides a README file. That's what cancer does, it destroys a shit ton of stuff. That's, definitely, what AIAD is. Cancer.

**Comment by Pigmoth69** [comment]
I totally agree Mr.Tomislaaaav! At least it could have something besides the readme.md to give us some AIAD carry!

**Comment by tomislaaaav** [comment]
AIAD is still cancer. Why is this issue closed? You need to fix it.

**Comment by jpedroteles** [comment]
Que chato Miguel
